language: python

python: "3.6"

git:
  depth: 1
  
install:
  - pip install -r requirements.txt
  - pip install codecov

script:
  - coverage run manage.py test

after_script:
  - bash <(curl -s https://codecov.io/bash)

after_success:
  - codecov