# Generated by Django 3.1.2 on 2020-11-22 12:22

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail')),
                ('username', models.CharField(max_length=254, verbose_name='Username')),
                ('first_name', models.CharField(max_length=254, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=254, verbose_name='Last Name')),
                ('phone_num', models.CharField(max_length=10, verbose_name='Phone Number')),
                ('address', models.CharField(max_length=125, verbose_name='Address')),
                ('raw_password', models.CharField(max_length=254, verbose_name='Password')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_num', models.CharField(default='NOT SET', max_length=10, verbose_name='Phone Number')),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail')),
                ('address', models.CharField(default='NOT SET', max_length=125, verbose_name='Address')),
                ('user', models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.TextField(default='', max_length=50, verbose_name='Event Name')),
                ('location', models.TextField(default='', max_length=80, verbose_name='Location')),
                ('short_description', models.TextField(default='', max_length=100, verbose_name='Short Description')),
                ('long_description', models.TextField(default='', max_length=255, verbose_name='Long Description')),
                ('number_people', models.IntegerField(default=2, verbose_name='Number of people')),
                ('date_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date and Time')),
                ('photo', models.ImageField(default='upload/images/no_img.png', null=True, upload_to='upload/')),
                ('arrange_time', models.DateTimeField(default='YYYY-MM-DD HH:MM[:ss[.uuuuuu]][TZ]', verbose_name='Arrangement Date and Time')),
                ('full', models.BooleanField(default=False)),
                ('user', models.CharField(default='', max_length=30, verbose_name="Host's Name")),
                ('participants', models.ManyToManyField(blank=True, default=0, null=True, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
