# Generated by Django 2.2.6 on 2020-11-05 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Kvent', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='photo',
            field=models.ImageField(default='upload/images/no-img.jpg', null=True, upload_to='upload/'),
        ),
    ]
