# Generated by Django 3.1.2 on 2020-11-08 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Kvent', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='host',
            field=models.CharField(default='', max_length=30, verbose_name="Host's Name"),
        ),
    ]
