# Generated by Django 3.1.2 on 2020-10-20 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Kvent', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='description',
            new_name='short_description',
        ),
        migrations.AlterField(
            model_name='event',
            name='date_time',
            field=models.TextField(default='2020-10-20 03:22:56', verbose_name='Date and Time'),
        ),
    ]
