# Generated by Django 3.1.2 on 2020-10-26 03:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Kvent', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='date_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date and Time'),
        ),
        migrations.AddField(
            model_name='event',
            name='participants',
            field=models.ManyToManyField(to='Kvent.Info'),
        ),
    ]
