# Generated by Django 3.1.2 on 2020-10-20 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Kvent', '0002_auto_20201020_0322'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='long_description',
            field=models.TextField(default='', max_length=255, verbose_name='Long Description'),
        ),
        migrations.AlterField(
            model_name='event',
            name='date_time',
            field=models.TextField(default='2020-10-20 03:36:05', verbose_name='Date and Time'),
        ),
        migrations.AlterField(
            model_name='event',
            name='short_description',
            field=models.TextField(default='', max_length=100, verbose_name='Short Description'),
        ),
    ]
