# Generated by Django 3.1.2 on 2020-11-08 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Kvent', '0002_event_host'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='participants',
            field=models.ManyToManyField(to='Kvent.Info'),
        ),
    ]
