# Generated by Django 3.1.1 on 2020-12-03 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Kvent', '0002_auto_20201203_1014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='photo',
            field=models.ImageField(default='https://storage.googleapis.com/kvent_bucket/upload/no_img.png', upload_to='upload/'),
        ),
    ]
