# Generated by Django 3.1.2 on 2020-11-08 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Kvent', '0003_event_participants'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=254, verbose_name='Username'),
        ),
    ]
