# Generated by Django 3.1.2 on 2020-10-20 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Kvent', '0004_auto_20201020_0601'),
        ('Kvent', '0002_auto_20201019_2118'),
    ]

    operations = [
    ]
