# Generated by Django 3.1.2 on 2020-11-08 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Kvent', '0004_auto_20201108_1247'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='participants',
        ),
        migrations.RemoveField(
            model_name='event',
            name='host',
        ),
        migrations.AddField(
            model_name='event',
            name='host',
            field=models.ManyToManyField(to='Kvent.Info'),
        ),
    ]
