# Generated by Django 3.1.2 on 2020-11-08 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Kvent', '0006_auto_20201108_1311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='host',
            field=models.TextField(default='', max_length=10, verbose_name="Host' Name"),
        ),
    ]
